.TH XMLSEC-CONFIG "1" "2002" "xmlsec-config" "User Commands"
.SH NAME
xmlsec-config \- manual page for xmlsec-config
.SH SYNOPSIS
.B xmlsec-config
[\fIOPTION\fR]...
.SH DESCRIPTION
Known values for OPTION are:
.TP
\fB\-\-prefix\fR=\fIDIR\fR
change XMLSEC prefix
.TP
\fB\-\-exec\-prefix\fR=\fIDIR\fR
change XMLSEC executable prefix
.TP
\fB\-\-libs\fR
print library linking information
.TP
\fB\-\-cflags\fR
print pre-processor and compiler flags
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information
.SH "SEE ALSO"
The full documentation for
.B xmlsec-config
is maintained as a Texinfo manual.  If the
.B info
and
.B xmlsec-config
programs are properly installed at your site, the command
.IP
.B info xmlsec-config
.PP
should give you access to the complete manual.
