.TH XMLSEC-CONFIG "1" "2002" "xmlsec-config" "User Commands"
.SH NAME
xmlsec-config \- script to get information about the installed
version of the XML Security Library
.SH SYNOPSIS
.B xmlsec-config
[\fIOPTION\fR]...
.SH DESCRIPTION
Known values for OPTION are:
.TP
\fB\-\-prefix\fR=\fIDIR\fR
change XMLSEC prefix
.TP
\fB\-\-exec\-prefix\fR=\fIDIR\fR
change XMLSEC executable prefix
.TP
\fB\-\-libs\fR
print library linking information
.TP
\fB\-\-cflags\fR
print pre-processor and compiler flags
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information
